# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-06 01:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20170506_0043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='fecha_publicacio',
            new_name='fecha_publicacion',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='commentario',
            new_name='comentario',
        ),
    ]
