# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-06 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('biografia', models.TextField()),
                ('sexo', models.CharField(choices=[('M', 'Mujer'), ('H', 'Hombre')], max_length=16)),
                ('genero_literario', models.CharField(choices=[('DR', 'Drama'), ('CM', 'Comedia'), ('FT', 'Fantasia'), ('CF', 'Ciencia Ficción'), ('PS', 'Poesia'), ('LC', 'Literatura Contemporanea'), ('LH', 'Literatura Hispana'), ('LU', 'Literatura Universal'), ('HS', 'Historica')], max_length=50)),
                ('edad', models.IntegerField()),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
